---
title: "SCFA package manual"
author: "Duc Tran"
date: "`r Sys.Date()`"
output:
    BiocStyle::html_document:
        toc: true
vignette: >
    %\VignetteIndexEntry{SCFA package manual}
    %\VignetteEngine{knitr::rmarkdown}
    \usepackage[utf8]{inputenc}
---

```{r knitr-options, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(fig.align = 'center', fig.width = 6, fig.height = 5, dev = 'png')
```

#Example
```{r, eval=TRUE}
#Download GBM dataset 
if(!file.exists("Example.rds")) download.file("https://bioinformatics.cse.unr.edu/software/scfa/Example/Example.rds", "Example.rds")
#Load example data (GBM dataset), for other dataset, download the rds file from the Data folder at https://bioinformatics.cse.unr.edu/software/scfa/Data/ and replace the Example.rds
GBM <- readRDS("Example.rds")
#List of three matrices from three data types
dataList <- GBM$data
#Survival information
survival <- GBM$survival
```

```{r, eval=TRUE}
library(SCFA)
library(survival)

#Generating subtyping result
set.seed(1)
subtype <- SCFA(dataList, seed = 1)

#Perform survival analysis on the result
coxFit <- coxph(Surv(time = Survival, event = Death) ~ as.factor(subtype), data = survival, ties="exact")
coxP <- round(summary(coxFit)$sctest[3],digits = 20)
print(coxP)
```

```{r, eval=TRUE}
#Split data to train and test
set.seed(1)
idx <- sample.int(nrow(dataList[[1]]), round(nrow(dataList[[1]])/2) )

survival$Survival <- survival$Survival - min(survival$Survival) + 1 # Survival time must be positive

trainList <- lapply(dataList, function(x) x[idx, ] )
trainSurvival <- Surv(time = survival[idx,]$Survival, event =  survival[idx,]$Death)

testList <- lapply(dataList, function(x) x[-idx, ] )
testSurvival <- Surv(time = survival[-idx,]$Survival, event =  survival[-idx,]$Death)

#Perform risk prediction
result <- SCFA.class(trainList, trainSurvival, testList, seed = 1)

#Validation using concordance index
c.index <- concordance(coxph(testSurvival ~ result))$concordance
print(c.index)
```

